project:
  type: website
  output-dir: docs
  resources: 
    - "*.xlsx"
    - "*.mgf"
    - "*.png"

website:
  title: "Hassan M. Hijazi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: histonePTM.Rmd
        text: My R package

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: FALSE
    page-layout: full

editor: visual